
services:
  # --- Servicio de Base de Datos Vectorial ---
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - ./long_term_memory:/qdrant/storage
    restart: unless-stopped

  # --- Servicio de Frontend/Debugging con Chainlit ---
  chainlit:
    build:
      context: .
      dockerfile: Dockerfile.chainlit
    ports:
      - "8000:8000"
    env_file:
      - .env
    # Nota: Solo necesitas QDRANT_URL para la comunicación entre contenedores.
    environment:
      - QDRANT_URL=http://qdrant:6333
    restart: unless-stopped
    volumes: 
      - ./short_term_memory:/app/data
    depends_on:
      - qdrant

  # --- Servicio de la App con Telegram ---
  telegram_app:
    image: ai-companion-app:telegram-v03
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - QDRANT_URL=http://qdrant:6333
    restart: unless-stopped
    volumes: 
      - ./short_term_memory:/app/data
    depends_on:
      - qdrant